name: Node.js Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build

      - run: npm publish --access public -w @om-dashboard/front-end
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
